config/routes.rb
Wedding::Application.routes.draw do
  get '/table/list' => 'table#list', as: 'table_list'
  get '/table/:id' => 'table#show'
  get '/people/list' => 'people#list', as: 'people_list'
  get '/photos' => 'photos#index', as: 'photos'
  resources :people
  root :to => 'people#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true

  # validates_uniqueness_of :seat_number, :scope => :table_number

  def name
    [last_name.upcase, first_name].delete_if { |n| n.blank? }.join(", ")
  end

  def full_name
    [first_name, last_name].delete_if { |n| n.blank? }.join(" ")
  end

  def photo_number=(value)
    self[:photo_number] = value.join(",")
  end

  def photo_number
    self[:photo_number].split(",") if self[:photo_number]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.order("last_name ASC")
  end

  def list
    index
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      flash[:success] = "Added #{@person.name}!"
      redirect_to new_person_path
    else
      flash[:danger] = "Could not add #{@person.name}."
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(person_params)
      flash[:success] = "Updated #{@person.name}'s details!"
      redirect_to session[:return_to] || people_path
      session[:return_to] = nil
    else
      flash[:danger] = "Could not update #{@person.name}."
      render :new
    end  
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    flash[:success] = "Removed #{@person.name}."
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit!
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    photo_numbers = 1.upto(40)
    @photos = Hash.new { |hash, key| hash[key] = [] }

    Person.all.each do |person|
      if person.photo_number
        person.photo_number.each do |num|
          @photos[num] << person unless num.blank?
        end
      end
    end
  end
end

app/controllers/table_controller.rb
class TableController < ApplicationController
  def show
    @people = Person.where(table_number: params[:id]).sort_by { |p| p.seat_number.to_i }
    render layout: false
  end

  def list
    session[:return_to] = request.fullpath
    @tables = Person.all
      .sort_by { |p| p.seat_number.to_i }
      .group_by(&:table_number)
      .sort_by { |t,_| t.to_i }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/table_helper.rb
module TableHelper
  def person_details(person)
    details = ["*"]
    case person.dietary_requirement
      when "Special"
        details << "S"
        details << person.other_requirements
      when "Dairy Free"
        details << "D"
      when "Gluten Free"
        details << "GF"
      when "Allergy"
        details << "Allergy #{person.other_requirements}"
    end
    details << "C" if person.age < 12
    "#{details.join(', ')}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wedding</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li <% if params[:controller] == "people" %>class='active'<% end %>><%= link_to "People", people_path %></li>
        <li <% if params[:controller] == "table" %>class='active'<% end %>><%= link_to "Tables", table_list_path %></li>
        <li <% if params[:controller] == "photos" %>class='active'<% end %>><%= link_to "Photos", photos_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</div>
<% flash.each do |k,v| %>
  <div class='alert alert-<%= k %>'><%= v %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name %>
      </div>

      <div class="form-group">
        <%= f.label :age %><br>
        <%= f.text_field :age %>
      </div>

      <div class="form-group">
        <%= f.label :table_number %><br>
        <%= f.select :table_number, (0..13).to_a, include_blank: true %>
      </div>

      <div class="form-group">
        <%= f.label :seat_number %><br>
        <%= f.select :seat_number, (1..12).to_a, include_blank: true %>
      </div>

      <div class="form-group">
        <%= f.label :photo_number %><br>
        <%= f.select :photo_number, (1..40).to_a, { include_blank: true }, { multiple: true, :class => "select2" }  %>
      </div>

      <div class="form-group">
        <%= f.label :dietary_requirement %><br>
        <%= f.select :dietary_requirement, ["Gluten Free", "Vegetarian", "Dairy Free", "Allergy", "Seafood", "Special"], { include_blank: true }, { :class => "select2" }  %>
      </div>

      <div class="form-group">
        <%= f.label :other_requirements %><br>
        <%= f.text_area :other_requirements, class: 'form-control input-md' %>
      </div>
    </div>

    <div class="col-md-6" id='table_info'>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1><%= @person.name %></h1>

<%= render "form" %>

app/views/people/index.html.erb
<h1>People</h1>

<%= link_to "Add new person", new_person_path, class: 'btn btn-primary' %>
<%= link_to "Name List", people_list_path, class: 'btn btn-primary' %>
<%= link_to "Table List", table_list_path, class: 'btn btn-primary' %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Table Number</th>
      <th>Seat Number</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><strong><%= link_to "#{person.last_name.upcase}, #{person.first_name}", [:edit, person] %></strong></td>
        <td><%= person.table_number %></td>
        <td><%= person.seat_number %></td>
        <td><%= link_to 'Remove', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/list.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Table Number</th>
      <th>Seat Number</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><strong><%= "#{person.last_name.upcase}, #{person.first_name}" %></strong></td>
        <td><%= person.table_number %></td>
        <td><%= person.seat_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>Add new person</h1>

<%= render "form" %>

app/views/photos/index.html.erb
<table class='table'>
  <% @photos.each do |number, people| %>
    <tr>
      <td><%= number %></td>
      <td><%= people.map(&:full_name).to_sentence %></td>
    </tr>
  <% end %>
</table>

app/views/table/list.html.erb
<% @tables.in_groups_of(8).each do |page| %>
  * = Bonbonerie, V = Vegetarian, VG = Vegan, GF = Gluten Free, F = Fructose Free, N = Nut Free, E = Egg Free, D = Dairy Free, S = Special (see note), C = Child
  <table class='seating'>
    <% page.in_groups_of(4).each do |tables| %>
      <tr>
        <% tables.compact.each do |table, people| %>
          <td width='25%' valign='top'>
            <table>
              <thead>
                <tr>
                  <td><h4>Table #<%= table %></h4></td>
                </tr>
              </thead>
              <tbody>
                <% people.each do |person| %>
                  <tr>
                    <td>
                      <strong><%= person.seat_number %></strong>
                      <%= link_to person.name, edit_person_path(person) %>
                      <strong><em><%= person_details(person) %></em></strong>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table><br><br><br><br><br>
<% end %>

app/views/table/show.html.erb
<h2>Table <%= params[:id] %></h2>

<% if @people.empty? %>
  Nobody is sitting at Table <%= params[:id] %> yet.
<% else %>
  <% @people.each do |person| %>
    <%= person.seat_number %>. <%= person.name %><br>
  <% end %>
<% end %>